### PR TITLE
fix: fixed issues with create, get, update and delete of discrete task

### LINKED ISSUE #4: fix: issue with create, get, delete and update of discrete task
**Describe the bug**
* When creating a discrete task, it would return an error because partial tasks weren't created yet
* When getting, updating and deleting a discrete task, req.body is used instead of req.params

### PR DESCRIPTION
**Pull request by shimoncohen**
| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Related issues: #4
Closes #4

### CODE REVIEW

File: src/DAL/repositories/discreteTaskRepository.ts [hunk 1]
```diff
@@ -14,15 +14,31 @@ export class DiscreteTaskRepository extends Repository<DiscreteTaskEntity> {
...
-    const exists = await this.exists(params);
-    if (!exists) {
+    const discrete = {
+      id: params.id,
+      version: params.version,
+      metadata: params.metadata,
+    };
+
+    // Check if discrete already exists
+    const exists = await this.exists(discrete);
```
Comment (cl-shaharshavit-rnd) [inline src/DAL/repositories/discreteTaskRepository.ts:30]: this check should probably be before casting logic

File: src/DAL/repositories/partialTaskRepository.ts [hunk 2]
```diff
@@ -45,9 +61,17 @@ export class PartialTaskRepository extends Repository<PartialTaskEntity> {
   }
 
   public async deletePartialTask(task: IPartialTaskParams): Promise<DeleteResult> {
-    // this.appLogger.log('info', `Deleting partial tasks for discrete "${discrete.id}" with version "${discrete.version}"`);
+    this.appLogger.log('info', `Deleting partial task with id "${task.id}"`);
```
Comment (cl-shaharshavit-rnd) [inline src/DAL/repositories/partialTaskRepository.ts:64]: add discreate details as task id don't have useful info on its on (if it isn't in the DB)

File: src/partialTask/models/partialTaskManager.ts [hunk 3]
```diff
@@ -16,6 +16,7 @@ export class PartialTaskManager {
   public async getPartialTasksByDiscrete(discrete: DiscreteTaskEntity, order: SearchOrder): Promise<IPartialTaskResponse[]> {
     const repository = await this.getRepository();
     const records = await repository.getAll(discrete, order);
+    console.log(`records: ${JSON.stringify(records)}`);
```
Comment (cl-shaharshavit-rnd) [inline src/partialTask/models/partialTaskManager.ts:19]: remove console

**Review by cl-shaharshavit-rnd — CHANGES_REQUESTED** [review]

**Review by cl-shaharshavit-rnd — APPROVED** [review]
